### PR TITLE
Make meetings non-editable, add all existing meetings to new timetable

### LINKED ISSUE #183: Add/Remove all meetings from the timetables when a new user is added

### LINKED ISSUE #184: Prevent user from editing meetings

### LINKED ISSUE #203: [PE-D] Lack of Edit command in Help command
self-explanatory bug, missing Edit command in Help

-------------
Labels: `severity.High` `type.DocumentationBug`
original: GlendonNotGlen/ped#4

### LINKED ISSUE #207: [PE-D] Missing fullstop in error message
-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: GlendonNotGlen/ped#6

### LINKED ISSUE #210: [PE-D] Unable to add lesson to users after exiting and restarting
This seems to be an issue caused by save.
Steps to reproduce:

1) Add users to the program  
2) Add a meeting for the users  
3) Add a new user  
4) Exit the program  
5) Restart the program  
6) Try adding lessons to users in list  

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: ngys117/ped#7

### PR DESCRIPTION
**Pull request by yanjie1017**
Fixes #203 
Update help command
Fixes #184 
Make meetings non-editable
Fixes #210 
Check if name not containing special characters
Fixes #207 
Format error messages
Fixes #183 
Add all existing meetings to new timetable

### CODE REVIEW

File: src/main/java/seedu/meetingjio/commands/AddUserCommand.java [hunk 1]
```diff
@@ -2,31 +2,49 @@
...
+import seedu.meetingjio.exceptions.OverlappingEventException;
 import seedu.meetingjio.timetables.MasterTimetable;
 import seedu.meetingjio.timetables.Timetable;
 
+import java.util.logging.Level;
+import java.util.logging.Logger;
+
 import seedu.meetingjio.exceptions.DuplicateTimetableException;
+
+import java.util.logging.Level;
```
Comment (angyongming) [inline src/main/java/seedu/meetingjio/commands/AddUserCommand.java:16]: Lines 11 and 16 seem to be duplicated. Perhaps can remove one of them?

**Comment by angyongming** [comment]
Everything looks good!
